version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis

  bot:
    build: .
    env_file: .env
    depends_on:
      - redis
    command: python -m src.bot

  redis:
    image: redis:7
    ports:
      - "6379:6379"
